package config

var AvailableRecipes = []string{
	// List out all the recipe names from cube_recipes.go
	"Perfect Amethyst",
	"Perfect Diamond",
	"Perfect Emerald",
	"Perfect Ruby",
	"Perfect Sapphire",
	"Perfect Topaz",
	"Perfect Skull",
	"Token of Absolution",
	"Upgrade El",
	"Upgrade Eld",
	"Upgrade Tir",
	"Upgrade Nef",
	"Upgrade Eth",
	"Upgrade Ith",
	"Upgrade Tal",
	"Upgrade Ral",
	"Upgrade Ort",
	"Upgrade Thul",
	"Upgrade Amn",
	"Upgrade Sol",
	"Upgrade Shael",
	"Upgrade Dol",
	"Upgrade Hel",
	"Upgrade Io",
	"Upgrade Lum",
	"Upgrade Ko",
	"Upgrade Fal",
	"Upgrade Lem",
	"Upgrade Pul",
	"Upgrade Um",
	"Upgrade Mal",
	"Upgrade Ist",
	"Upgrade Gul",
	"Upgrade Vex",
	"Upgrade Ohm",
	"Upgrade Lo",
	"Upgrade Sur",
	"Upgrade Ber",
	"Upgrade Jah",
	"Upgrade Cham",
	"Add Sockets to Weapon",
	"Add Sockets to Armor",
	"Add Sockets to Helm",
	"Add Sockets to Shield",
	"Reroll GrandCharms",
	"Caster Amulet",
	"Caster Ring",
	"Caster Belt",
	"Caster Boots",
	"Blood Amulet",
	"Blood Ring",
	"Blood Gloves",
	"Blood Boots",
	"Blood Belt",
	"Blood Helm",
	"Blood Armor",
	"Blood Weapon",
	"Safety Shield",
	"Safety Armor",
	"Safety Boots",
	"Safety Gloves",
	"Safety Belt",
	"Safety Helm",
	"Hitpower Gloves",
	"Hitpower Boots",
	"Hitpower Belt",
	"Hitpower Helm",
	"Hitpower Armor",
	"Hitpower Shield",
}
